### ISSUE TITLE
Triggers isn't working on gamecube

### ISSUE THREAD

**Issue by bruno-oliveira1** [darthcloud/BlueRetro#753]
### BlueRetro firmware version

1.8.4

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

Universal

### BlueRetro hardware type

External adapter with detachable cord

### Manufacturer

BlueRetro Gaming Store

### System used

Nintendo GameCube

### Bluetooth controller brand & name

8bitdo Ultimate, Gamesir T4 pro, 8bitdo M30, 8bitdo SN30 Pro

### What is problem? (only list ONE problem per report)

When I paired one of this controllers using Switch mode the triggers works fine but when a pair the second one using Switch or Xinput the triggers stop working on both of them, using Visual_Controller_Test https://wiibrew.org/wiki/Visual_Controller_Test, I had the proof of this failure. 

### What did you expect to happen?

Pair more than one controller and works fine

### Attach files like logs or Bluetooth traces here

-----------------------------------------------------
8bitdo Ultimate (Button pressed order)
Left analog up
Left analog down
Left analog left
Left analog right
dpad up
dpad down
dpad left
dpad right
home
-
star 
+
Y
X
A
B
right analog up
right analog down
right analog left
right analog right
L3
R3
P1
P2

Gamesir T4 PRO 
LT
LB
RT
RB
Left analog up
Left analog down
Left analog left
Left analog right
dpad up
dpad down
dpad left
dpad right
home
select
start
turbo
Y
X
A
B
right analog up
right analog down
right analog left
right analog right
L3
R3
M1
M2
M3
M4
[trace_files.zip](https://github.com/darthcloud/BlueRetro/files/12399145/trace_files.zip)

**Comment by DragonKumera** [comment]
I noticed l and r were not working on mine (internal blue tooth) to

**Comment by darthcloud** [comment]
Try to reload the merge trigger preset:
https://github.com/darthcloud/BlueRetro/wiki/BlueRetro-BLE-Web-Config-User-Manual#33---example-preset-load

**Comment by DragonKumera** [comment]
reloading 1.8.3 firmware solved the problem. Definitely an issue with 1.8.4 firmware. Even deleted all the 4 files in file manager to test and same issue on 1.8.4.

**Comment by bruno-oliveira1** [comment]
> reloading 1.8.3 firmware solved the problem. Definitely an issue with 1.8.4 firmware. Even deleted all the 4 files in file manager to test and same issue on 1.8.4.



> Try to reload the merge trigger preset: https://github.com/darthcloud/BlueRetro/wiki/BlueRetro-BLE-Web-Config-User-Manual#33---example-preset-load

I'd already did and got the same problem.

**Comment by DragonKumera** [comment]
> > reloading 1.8.3 firmware solved the problem. Definitely an issue with 1.8.4 firmware. Even deleted all the 4 files in file manager to test and same issue on 1.8.4.
> 
> I'll try today

Do let us know if it worked!

**Comment by bruno-oliveira1** [comment]
Worked !!!!!, after downgrading to 1.8.3. Thank you guys.

**Comment by DragonKumera** [comment]
> Worked !!!!!, after downgrading to 1.8.3. Thank you guys.

Great to hear! Now I hope 1.8.4 can get fixed

**Comment by darthcloud** [comment]
Are you sure you got the merged trigger preset loaded as in this example?
https://github.com/darthcloud/BlueRetro/wiki/BlueRetro-BLE-Web-Config-User-Manual#33---example-preset-load

So I tested this myself in v1.8.4 with 8bitdo SF30 and Ultimate controllers. I had the merged trigger preset loaded and in Wario World I was able to dash with R and also Slam the ground with A then R.

Can you guys run homebrew?

If so run this https://github.com/corenting/GC-Controller-Test/releases/tag/v1.2

and take a picture while you hold R to maximum and post here. I want to see the analog value.

Also can you take a screenshot of the mapping in the web configuration ( i need to see the first 32 entries)

**Comment by DragonKumera** [comment]
> Are you sure you got the merged trigger preset loaded as in this example? https://github.com/darthcloud/BlueRetro/wiki/BlueRetro-BLE-Web-Config-User-Manual#33---example-preset-load
> 
> So I tested this myself in v1.8.4 with 8bitdo SF30 and Ultimate controllers. I had the merged trigger preset loaded and in Wario World I was able to dash with R and also Slam the ground with A then R.
> 
> Can you guys run homebrew?
> 
> If so run this https://github.com/corenting/GC-Controller-Test/releases/tag/v1.2
> 
> and take a picture while you hold R to maximum and post here. I want to see the analog value.
> 
> Also can you take a screenshot of the mapping in the web configuration ( i need to see the first 32 entries)

Yeas I used the exlene gamecube controller pre config. Works perfectly on 1.8.3 but fails on 1.8.4

**Comment by darthcloud** [comment]
Well this bug is about the 8bitdo controllers. I'll look at the other bug later.

**Comment by psicotron3** [comment]
> Well this bug is about the 8bitdo controllers. I'll look at the other bug later.

@darthcloud I think this issue is related to #849.

I just commented there that digital triggers only work if digital and analog triggers are merged. Digital triggers can't be mapped alone.

Is that behavior intentional?

**Comment by ANK-dev** [comment]
@darthcloud Triggers also stop working when 2 or more DualSense controllers are connected to the same BlueRetro device. Tested on a Wii via the GameCube ports on firmware 1.9.1.

**Comment by DragonKumera** [comment]
> @darthcloud Triggers also stop working when 2 or more DualSense controllers are connected to the same BlueRetro device. Tested on a Wii via the GameCube ports on firmware 1.9.1.

Been having that problem since um I think 2 versions ago. Work around was getting all 4 exelene gamecube controllers connected and pressing l+r at the same time. or 3 holding it down while the last presses it and it normally happens. (can easily test this in mario kart double dash for the randomizer option)

**Comment by darthcloud** [comment]
This beta should fix it:
https://github.com/darthcloud/BlueRetro/actions/runs/8680779369

**Comment by darthcloud** [comment]
Fixed in v24.04

**Comment by littlemisskittn** [comment]
Issue is still prevalent. Despite me setting the preset correctly, Xbox Series X controller STILL cannot perform slam in Wario World.
