### ISSUE TITLE
Trigger R not working in gamecube game Wario World

### ISSUE THREAD

**Issue by pablopsw** [darthcloud/BlueRetro#766]
### BlueRetro firmware version

v1.8.4

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

System specific

### BlueRetro hardware type

Internal install DIY

### Manufacturer

Myself

### System used

Nintendo GameCube

### Bluetooth controller brand & name

Original Dualshock 3 and 4 controller

### What is problem? (only list ONE problem per report)

R trigger does not work in gamecube game Wario World, I tried different settings in advanced settings, placing R trigger on other buttons and the problem persists.

### What did you expect to happen?

that the trigger R worked

### Attach files like logs or Bluetooth traces here

https://github.com/darthcloud/BlueRetro/assets/75383650/f4bd35ab-623d-41fb-8a48-67efabac34c0

![image](https://github.com/darthcloud/BlueRetro/assets/75383650/ee02abe2-790a-471e-8337-c7f9d566ad55)

**Comment by kirimui** [comment]
I have the same problem, I was on 1.8.3, I updated to 1.8.4 and it still doesn't work.

**Comment by rattboi** [comment]
I've tried this now, to confirm. It's weird, but yeah it doesn't work. 

I used the gc-controller-test app and it all looks right there, with merged triggers. I can't tell the difference in that app between wired gc controller and bluetooth one.

**Comment by darthcloud** [comment]
So I tested this myself in v1.8.4 with PS5, PS4, PS3 and Switch controllers. I had the merged trigger preset loaded and I was able to dash with R and also Slam the ground with A then R.

Can you guys run homebrew?

If so run this https://github.com/corenting/GC-Controller-Test/releases/tag/v1.2

and take a picture while you hold R to maximum and post here. I want to see the analog value.

**Comment by pablopsw** [comment]
It's the only game that happens to me. Thanks for your time.
![WhatsApp Image 2023-09-23 at 17 10 15 (1)](https://github.com/darthcloud/BlueRetro/assets/75383650/4835870c-a399-49ba-925c-1c232bf669d4)
![WhatsApp Image 2023-09-23 at 17 10 15 (2)](https://github.com/darthcloud/BlueRetro/assets/75383650/5717deaf-9d78-4d90-835c-8d39d1a8635e)
![WhatsApp Image 2023-09-23 at 17 10 15](https://github.com/darthcloud/BlueRetro/assets/75383650/f97ae564-f500-478f-872d-19bfc2ceaa5d)

**Comment by darthcloud** [comment]
@pablopsw base on screenshot of first post you don't have the merge trigger preset that the gamecube end trigger require.

See https://github.com/darthcloud/BlueRetro/wiki/BlueRetro-BLE-Web-Config-User-Manual#33---example-preset-load

With that preset the L & R end button will get pressed when the analog value reach >= 197

**Comment by pablopsw** [comment]
It worked! I needed to read a little more, thank you for answering me and solving the problem.

**Comment by darthcloud** [comment]
Closing as original author problem is fixed, but @kirimui & @rattboi feel free to post your analog value and screenshot of mapping.

**Comment by sushimehl** [comment]
Sorry but I still have this problem with my 8bitdo Pro2... I guess it's like this because i always need to change the mapping of ABYX again to work correctly, as shown on my screenshot, every time I try the merge trigger preset... Strangely enough, this is only a problem on my Gamecube, on my Wii the R button works flawless with this Game... But I still need to keep the Button mapping like on my screenshot. Any clue why?
![Pro2 NGC](https://github.com/darthcloud/BlueRetro/assets/35766134/aa1c6158-75d9-404b-b6fd-a4d344b3e12b)
